Update README.md
ember-learn/guidemaker-ember-template pull request #195
Opened 2024-06-30 00:43 UTC by raspberri05

issue #193. Added back the readme contents lost during v2 conversion. Please let me know if this if fine or if some things need to be removed. I currently just switched it back to the readme that had all the information.

2024-06-30 06:56 UTC, IgnaceMaes requested changes
Can the current README template be used, but with the description of the old one?

Some sections no longer apply:
- The old compatibility info should be replaced with the new one
- The old running instructions are not applicable anymore. The new ones can be found here: https://github.com/ember-learn/guidemaker-ember-template/blob/main/CONTRIBUTING.md.

2024-07-01 20:13 UTC, raspberri05 commented
Hi i've made the changes. Not sure why it didnt add my new commits to this PR so I opened another PR: https://github.com/ember-learn/guidemaker-ember-template/pull/197

Wasnt sure if you still wanted to releases section so I've kept it. thanks

2024-07-01 20:17 UTC, raspberri05 commented
Hi i made the changes and added the commits to this PR. Not sure if you wanted to put the releases section back but I did anyways, please let me know if further changes are needed. Thanks

2024-07-02 13:43 UTC, mansona commented on README.md
> +------------------------------------------------------------------------------
we should not use this style of headers any more

2024-07-02 17:26 UTC, raspberri05 commented
I've made the requested changes. Please let me know if anything else needs to be changed before merging this.

2024-07-07 21:07 UTC, closed without merging

2024-07-08 09:31 UTC, mansona commented
@raspberri05 it looks like you deleted your fork so we're not able to merge this any more? 🤔 was that a mistake?

2024-07-19 12:44 UTC, driesdl commented
@mansona shall i make a new PR with the changes above in it?